---
title: "assignment-1"
author: "Sarthak-18204342"
date: "2 October 2018"
output: pdf_document
---



## Task-1 Manipulation 
```{r}

# Question-1
# Load the dataset

# 1. Load the dataset EurostatCrime2015.csv. Notice that the first column of the csv
# file contains the names of the countries that must be read as row names [Hint: Load
# in the file using the function read.csv]. [0.5]

crime_data <- read.csv("../../data/EurostatCrime2015.csv")

```

```{r}
#2. What is the size and the structure of this dataset? [0.3]
print(ncol(crime_data)) # number of columns
print(nrow(crime_data)) # number of rows
print(str(crime_data)) # structure of the data
 
```

```{r}
#3. Produce appropriate commands to answer the following questions:
#(i) Add a new column called Sex.crime which contains the sum of all the crimes
#that have a sexual component: Rape, Sexual.assault and Sexual.violence
#[1]
#(ii) remove the columns Rape, Sexual.assault and Sexual.violence. [1]

crime_data$Sex.crime = crime_data$Sexual.assault + crime_data$Sexual.violence + crime_data$Rape
#head(crime_data, n = 10)


crime_dataset_new = subset(crime_data, select = -c(Rape, Sexual.assault, Sexual.violence))
head(crime_dataset_new, n = 5)
```
```{r}
#4. Work with the dataset you created in question (3ii), and list the countries that
# contain any missing data.

#sapply(crime_dataset_new, function(x) sum(is.na(x)))

crime_dataset_new[!complete.cases(crime_dataset_new),1]
#complete.cases(crime_dataset_new)

# to delete  x <- na.omit(crime_dataset_new)
```
```{r}
# 5. Remove the countries with missing data from the dataframe.

crime_dataset_filtererd <- na.omit(crime_dataset_new)
head(crime_dataset_filtererd,n=30)


```

```{r}
# 6. What is the size of this new dataframe?
str(crime_dataset_filtererd)

```

```{r}
# TASK-2

# 1. According to these data what was the most common crime in Ireland in 2015?

#colnames(crime_dataset_filtererd[5])

#head(crime_dataset_filtererd, n = 30)
ireland_data <- crime_dataset_filtererd[crime_dataset_filtererd$X == "Ireland",]
#print(ireland_data)

max_value <- apply(ireland_data[,2:6],1,max)
 # get column name whos value is the max value
print("Most Common Crime in Ireland:")
print(colnames(ireland_data)[which(ireland_data==max_value, arr.ind=TRUE)][2])
#print(max_value)
```

```{r}
# 2. And the 3 least common crimes in Ireland in 2015?
# Get 3 values and the common names related to aove q
print("3 Least common crimes in Ireland ascending order:")
min_value <- apply(ireland_data[,2:6],1,min)
print(colnames(ireland_data)[which(ireland_data==min_value, arr.ind=TRUE)][2])

ireland_data_2 <- subset(ireland_data, select = -c(Intentional.homicide))
min_value <- apply(ireland_data_2[,2:5],1,min)
print(colnames(ireland_data_2)[which(ireland_data_2==min_value, arr.ind=TRUE)][2])

ireland_data_3 <- subset(ireland_data_2, select = -c(Robbery))
min_value <- apply(ireland_data_3[,2:4],1,min)
print(colnames(ireland_data_3)[which(ireland_data_3==min_value, arr.ind=TRUE)][2])
```

```{r}

#3. Which country have the highest record of offences (per hundred thousand inhabitants)?
crime_dataset_filtererd$total_offences = crime_dataset_filtererd$Assault + crime_dataset_filtererd$Intentional.homicide + crime_dataset_filtererd$Robbery + crime_dataset_filtererd$Theft + crime_dataset_filtererd$Sex.crime

#crime_dataset_filtererd

max_values_offences <- max(crime_dataset_filtererd$total_offences)
print(max_values_offences)
#colMax <- function(data) sapply(data, max, na.rm=TRUE)
#max_values_offences = colMax(crime_dataset_filtererd$total_offences)

index_country_max_offences = rownames(crime_dataset_filtererd)[which(crime_dataset_filtererd==max_values_offences, arr.ind = TRUE)][1]


#print(crime_dataset_filtererd$X[which(crime_dataset_filtererd$total_offences==max_values_offences)][1])
v <- crime_dataset_filtererd$X[which(crime_dataset_filtererd$total_offences==max_values_offences)]

sprintf("Country having the highest record of offences: %s", v)

```

```{r}

# TASK-3

assault <- crime_dataset_filtererd$Assault
barplot(assault, xlab = "Assault", ylab="Frequency")

Intentional.homicide <- crime_dataset_filtererd$Intentional.homicide
barplot(Intentional.homicide, xlab = "Intentional.homicide", ylab="Frequency")

Robbery <- crime_dataset_filtererd$Robbery
barplot(Robbery, xlab = "Robbery", ylab="Frequency")

Theft <- crime_dataset_filtererd$Theft
barplot(Theft, xlab = "Theft", ylab="Frequency")

Sex.crime <- crime_dataset_filtererd$Sex.crime
barplot(Sex.crime, xlab = "Sex.crime", ylab="Frequency")

```

```{r}
print("This dispays the correlation of each of these values.")
plot(crime_dataset_filtererd[2:6])
```




