---
title: "tutorial R"
output: html_document
---

```{r}

# DATA TYPES

# vectors
apple <- c('red','green','yellow')
print(apple)
print(class(apple))

# lists
list1 <- list(c(2,3,2), 3.14, sin)
print(list1)


# Matrices
M = matrix(c('a','b','b','a','b','b','c','d'), nrow=2, ncol=4, byrow=TRUE)
print(M)


# Arrays
a <- array(c('green','yellow','black','orange'), dim=c(3,3,2))
# The above line adds items in single column then move to next column and keep repeating
print(a)


# Factors
apple_colors <- c('g','g','b','y','b','y')
factor_apple <- factor(apple_colors)
print(apple_colors)
print(factor_apple) # sorts alphabetical too


# Dataframes
# unlike arrays it has different modes of data but with equal length
BMI <- data.frame(
  Gender = c("male","male","female"),
  Height = c(158,165,155),
  Weight = c(65,70,73),
  Age = c(22,24,19)
)
print(BMI)
```

```{r}
# VARIABLES

c(TRUE,1) -> var.3

print(var.3)
cat ("var.3 is ", var.3 ,"\n")

# A variable does not have it's own data type. 
# The data type of the object is assigned to it

# prints all the variables declared in the environment
# variables starting with . are hidden by default use all.names=TRUE to view them
print(ls(all.names=TRUE)) 

rm(str_1)  # To delete a variable
# to remove all the variables rm(list=ls())
```

```{r}
# OPERATORS

# Arthematic: + - * / %% 
a <- 5
b <- 7
print(a%%b)
print(a%/%b)
print(2^3)

# Logical: 
# & Element Wise
# | Element Wise
# ! Element Wise
# && takes first element of both vectors
# || takes first element of both vectors


# Assignment Operators = or <- or <<-    -> or ->>

# Misc: 
# %in% if element belongs to vector
# %*%  to multiply matrix with it's transpose M1 = M %*% t(M)

```

```{r}
# LOOPS


v <- c("hello")
v2 <- LETTERS[2:6]
count <- 3

repeat {
  print(v)
  count <- count + 1
  
  if(count > 3) {
    break
  }
}

while(count < 4) {
  print(v)
  count <- count + 1
}

for (i in v2) {
  if (i == "D") {
    next()
  }
  print(i)
}

```

```{r}

# FUNCTIONS
FindRemainder <- function(a,b) {
  print(a %% b)
}

FindRemainder(10,3)


# STRINGS

# To combine the strings 
s1 <- "Dick"
s2 <- "Head"
print(paste(s1,s2, sep="*"))
print(paste(s1,s2, sep="", colapse=""))


result1 <- format(23.1234556, digits=3, scientific=FALSE, width=7)
result2 <- format("Hello", width = 8, justify = "c")
print(result1)
print(result2)

# to count the number in a string
print(nchar("Hello"))
print(toupper("Hello"))
print(substring("Hello",1,4))

```

```{r}

# VECTORS

v <- 3.5:7.2
print(v)

print(seq(5,7, by=0.3))

# accessing vectors
# access vectors by 0,1 at positions and T or F at positions
t <- c("Sun","Mon","Tue","Wed","Thurs","Fri","Sat")
u <- t[c(2,3,6)]
print(u)


v1 <- c(3,8,4)
v2 <- c(4,11,0,8,1,2)
print(v1+v2)
print(sort(v1+v2, decreasing=TRUE))
```

```{r}

# LISTS

list_data <- list(c("Jan","Feb","Mar"), matrix(c(3,9,5,1,-2,8), nrow = 2),
   list("green",12.3))
names(list_data) <- c("1st Quarter", "A_Matrix", "A Inner list")
print(list_data)

list_data[3] <- NULL
print(list_data)

# to merge list 
# merged.list <- c(list1,list2)

# convert list to vectors
v4 <- unlist(list_data)
print(v4)
print(length(v4))
```
```{r}

# ARRAYS
# to store the data in more than 2 dimensions

vector1 <- c(5,9,3)
vector2 <- c(10,11,12,13,14,15)

result <- array(c(vector1,vector2), dim=c(3,3,2))
print(result)
print(result[,,2]) # prints the second matrix

# c(1) sum of the rows
# c(2) sum of the columns
# c(3) sum of the individual matrices
new_result <- apply(result, c(3), sum)
print(new_result)
```

```{r}
# FACTORS
# Categorize the data and store the data in levels

data <- c("low","med","low","high","low","med")
factor_data <- factor(data, levels=c("low","med","high"))
print(factor_data)

generated_factor_data <- gl(3,4, labels=c("Delhi","Haryana","Punjab"))
print(generated_factor_data)

```

```{r}

# DataFrames

emp.data <- data.frame(
  emp_id  = c(1:3),
  emp_name = c("Rick","Morty","Ryan"),
  salary = c(20000, 30000, 25000),
  stringsAsFactors = FALSE
)

# Extract Specific Columns
result1 <- data.frame(emp.data$emp_name, emp.data$salary)
print(result1)

result2 <- emp.data[c(1,3), c(2)]
print(result2)

# to add the rows or merge 2 datasets
# result <- rbind(table1, table2)
```

```{r}
# PACKAGES

# .libPaths()
# library()
# search()
# install.packages("Package Name")

# to load a package in the library
# library("package name", lib.loc = "path to library") 
```
```{r}

# DATA RESHAPING

# melt(dataframe_name, id=c("col1","col2"))
# converts to [col1 - col2 - variable - value]

# cast(dataframe_name, col1+col2~variable, sum)
# which ever row has col1 and col2 and have an extra col then add them to the same row.
```

